# Generated by Django 4.2.4 on 2023-08-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='dia_de_venda',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
