# Generated by Django 4.2.4 on 2023-08-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_venda_data_alter_venda_data_venda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
