# Generated by Django 4.2.4 on 2023-08-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_produto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/fotos_produtos'),
        ),
    ]
