# Generated by Django 5.0.7 on 2024-09-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='data_servico',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='valor_total',
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome_servico',
            field=models.CharField(max_length=255),
        ),
    ]
