# Generated by Django 5.0.7 on 2024-09-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_rename_data_servico_servico_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='nome_servico',
            new_name='servico_prestado',
        ),
    ]
